openapi: 3.0.0
info:
  title: User register API
  version: 1.0.0
paths:
  /api/register:
    post:
      summary: User register
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - email
                - password
                - firstName
                - lastName
                - role
                - photos
              properties:
                email:
                  type: string
                  description: User's email address.
                password:
                  type: string
                  description: User's password.
                firstName:
                  type: string
                  description: User's first name.
                lastName:
                  type: string
                  description: User's last name.
                role:
                  type: string
                  description: User's role (e.g., admin).
                photos:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: User's photos (multiple files allowed).
      responses:
        '201':
          description: User signed up successfully.
  /api/login:
    post:
      summary: User Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  description: User's email address.
                password:
                  type: string
                  description: User's password.
      responses:
        '200':
          description: User logged in successfully.
        '400':
          description: Invalid credentials.
  /api/users/me:
    get:
      summary: Get Current User
      produces:
        - application/json
      responses:
        '200':
          description: Successful operation. Returns the current user's information.
        '401':
          description: Unauthorized. User is not authenticated.